# /Users/stevenmurray/PycharmProjects/pyBingeBuddy/.streamlit/secrets.toml

TMDB_API_KEY = "your_tmdb_api_key"
SMTP_HOST = "smtp.zoho.com"
SMTP_PORT = 587
SMTP_USE_TLS = "true"
SMTP_USER = "binge.buddy@mightymiraclemax.com"
SMTP_PASS = "bbA2025!"
ALERT_EMAIL_TO = "murraysc@gmail.com"

SQLITE_CLOUD_URL = "sqlitecloud://cmnfss5rnk.g3.sqlite.cloud:8860?apikey=i6JHgbJgkTYpC6gVfbSRrOwi2MsBt8GJpXoR4HazRlk"
SQLITE_DB = "pyBingeBuddy"
